# Generated by Django 5.0.3 on 2024-03-08 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='PropertyModel',
            new_name='Property',
        ),
        migrations.RenameModel(
            old_name='ReplyModel',
            new_name='Reply',
        ),
        migrations.RenameModel(
            old_name='ReviewModel',
            new_name='Review',
        ),
    ]
