# Generated by Django 5.0.3 on 2024-03-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0004_alter_property_options_property_landlord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='room_type',
        ),
        migrations.AddField(
            model_name='property',
            name='eircode',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
