version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install --upgrade pip
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/*.py --disable=C,R,E1101
            - pylint $CODEBUILD_SRC_DIR/RentRater/*.py --disable=C,R,E1101
            - pylint $CODEBUILD_SRC_DIR/rater/*.py --disable=C,R,E1101
artifacts:
    files:
        - '**/*'