version: 0.2
phases:
    # install python environments and required library for application, install pylint
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install --upgrade pip
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
            
    # Run pylint on python files
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/*.py --disable=C,R
            - pylint $CODEBUILD_SRC_DIR/RentRater/*.py --disable=C,R
            # Disable false positive messages using --disable parameters
            - pylint $CODEBUILD_SRC_DIR/rater/*.py --disable=C,R,W0622,W0611,E1101,W0613
artifacts:
    files:
        - '**/*'